channels:
    - conda-forge
    - cpape
name:
    elf-dev
dependencies:
    - imageio
    - h5py
    - mrcfile
    - nifty
    - pandas
    - python 3.7
    - pip
    - scikit-image
    - tqdm
    - vigra
    - z5py
