channels:
    - conda-forge
name:
    elf-dev
dependencies:
    - affogato
    - imageio
    - h5py
    - mrcfile
    - nifty >=1.1
    - numba
    - pandas
    - python
    - pip
    - scikit-image
    - skan
    - tqdm
    - vigra
    - zarr
    - z5py
